In [15]:
import pandas as pd
df = pd.read_csv('csvfiles/7Xo1lV6o6vP5H062.csv')

In [16]:
df.head()

,Serial Number,Filename,Description,Gender,Attributes,UUID,HASH
0,21,abdul-the-vibe,abdul the life of the party and can never be c...,male,NaN,770f817a-9d9a-4772-9a91-e66dd9d03470,NaN
1,22,emeka-the -clown,"emeka the funny man, always making silly jokes",male,NaN,78810fa6-a7ef-4d83-bf57-caf49db4ee69,NaN
2,23,salam-the-odogwu,salam is a big time textile marketer always so...,male,NaN,f2957ded-022c-4b07-92c6-b345d4816a67,NaN
3,24,charles-the-exporter,charles a business man an importer and exporte...,male,NaN,09395e76-19ed-4852-8748-795ee7496a8e,NaN
4,25,wole-the-pimp,wole knows all the babes in town and is always...,male,NaN,4d94d4f7-9b69-4e43-9db1-1fe83df92857,NaN

In [7]:
df_2 = df.reset_index(drop=True)

In [8]:
df_2

,Serial Number,Filename,Description,Gender,UUID,HASH
0,21,abdul-the-vibe,abdul the life of the party and can never be c...,male,770f817a-9d9a-4772-9a91-e66dd9d03470,NaN
1,22,emeka-the -clown,"emeka the funny man, always making silly jokes",male,78810fa6-a7ef-4d83-bf57-caf49db4ee69,NaN
2,23,salam-the-odogwu,salam is a big time textile marketer always so...,male,f2957ded-022c-4b07-92c6-b345d4816a67,NaN
3,24,charles-the-exporter,charles a business man an importer and exporte...,male,09395e76-19ed-4852-8748-795ee7496a8e,NaN
4,25,wole-the-pimp,wole knows all the babes in town and is always...,male,4d94d4f7-9b69-4e43-9db1-1fe83df92857,NaN
5,26,saro-the-baller,saro is a baller and is always ready to turnup,male,d35a7514-8996-42fb-a5f2-5a603ec679c5,NaN
6,27,ade-omo-yoruba,ade a yourba man takes pride in the yourba tribe,male,92984fa0-310b-4377-8a10-15965d044383,NaN
7,28,shola-cool-kid,shola prefers to be alone because he hates stress,male,3ac5c186-bc14-4eb6-8567-cc818465a64f,NaN
8,29,charlie-the-smoker,charlie uses smoking as a coping mechanism,male,71a0aa22-d111-43b7-8484-43d87310bc42,NaN
9,30,femi-the-badguy,femi is the biggest guy in lagos and he has se...,male,e493e3fb-a8a0-455a-854f-0f6474bbc69f,NaN
10,31,sinzu-money,sinzu loves spending money on flashy things,male,942f8347-9932-4331-bd15-d0f3a048b54f,NaN
11,32,obinna-the-palmwine tapper,obinna taps palmwine for a living,male,0f1af056-2548-4407-bed4-abc11deae05d,NaN
12,33,aminu-maikudi,aminu is a wealthy man from a family with gene...,male,0129e7a5-e3d0-4675-92d0-1a1e55d11612,NaN
13,34,sabinus-the-town crier,sabinus delivers messages to his town people,male,01d4ce96-818e-44b1-8813-68a7d34b35ba,NaN
14,35,adisa-ibadan,adisa the greatest man in the whole town of ib...,male,3a925f27-35f6-4dbf-9960-c6527fae5f3e,NaN
15,36,linda-the-navigator,linda knows how to make a way for herself and ...,female,71f335a6-5a4f-4410-9cea-179336f0e498,NaN
16,37,kemi-the-iron lady,kemi the strongest woman known to the town of ...,female,35b11a31-5b92-49f4-8fb1-30f255d22054,NaN
17,38,mercy-the-sassy lady,mercy only care about spending her father's mo...,female,7a3c70ac-927f-4a63-a3df-ab86dd27cd0f,NaN
18,39,sandra-money,sandra likes getting and spending money,female,1bd95fb0-7b2e-4354-bebd-22f9cf70a1ca,NaN
19,40,bimpe-the-fashionista,bimpe loves wearing trendy clothes and looking...,female,92b548b7-998b-46b6-8198-80d407209483,NaN